# Generated by Django 5.1.1 on 2024-09-29 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_areatrabajo_rename_project_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areatrabajo',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='areatrabajo',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='areatrabajo',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.division'),
            preserve_default=False,
        ),
    ]
