# Generated by Django 4.2.16 on 2024-10-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_areatrabajo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='divisiones/'),
        ),
    ]
