# Generated by Django 5.1.1 on 2024-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_division_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
