# Generated by Django 5.1.1 on 2024-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_division_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='fotografia',
            field=models.ImageField(default='imagen', upload_to='imagenes/'),
        ),
    ]
