# Generated by Django 4.2.16 on 2024-10-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_division_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
    ]
