# Generated by Django 4.2.16 on 2024-10-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatrabajo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
