# Generated by Django 4.2.16 on 2024-10-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
