# Generated by Django 4.2.16 on 2024-10-14 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areatrabajo',
            name='archivo',
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('area_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='myapp.areatrabajo')),
            ],
        ),
    ]
