# Generated by Django 4.2.16 on 2024-10-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_areatrabajo_archivo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
