# Generated by Django 4.2.16 on 2024-10-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_documento_nombre_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion_documento',
            field=models.CharField(default='[No informacion]', max_length=2000),
        ),
        migrations.AlterField(
            model_name='areatrabajo',
            name='descripcion',
            field=models.CharField(default='[No informacion]', max_length=2000),
        ),
    ]
