# Generated by Django 4.2.16 on 2024-10-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_areatrabajo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='descripcion',
            field=models.CharField(default='w', max_length=2000),
        ),
    ]
