# Generated by Django 4.2.16 on 2024-10-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_areatrabajo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='descripcion',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion_documento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
