# Generated by Django 4.2.16 on 2024-10-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_areatrabajo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(max_length=1000),
        ),
    ]
